name: Self-hosted Smoke

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: [self-hosted, macOS]
    steps:
      - run: |
          whoami
          uname -a
          pwd
